version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/img:/app/img
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://client:3000 