name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: server/requirements.txt
    
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Install server dependencies
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run ESLint
      working-directory: ./client
      run: npm run lint
    
    - name: Build client
      working-directory: ./client
      run: |
        # Disable telemetry
        npx next telemetry disable
        # Run build with production environment
        NODE_ENV=production npm run build
      env:
        NEXT_TELEMETRY_DISABLED: 1
        # Add any other environment variables your app needs
        NEXT_PUBLIC_API_URL: http://localhost:8000
    
    - name: Run client tests
      working-directory: ./client
      run: npm test
      if: false  # Set to true when you have tests
    
    - name: Run server tests
      working-directory: ./server
      run: |
        python -m pytest
      if: false  # Set to true when you have tests 